name: Build scratch image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Buildah
        run: |
          sudo apt update
          sudo apt install -y buildah

      - name: Build image (scratch)
        run: |
          buildah unshare ./build.sh

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | buildah login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          buildah tag scratch-static-web ghcr.io/$OWNER/scratch-static-web:latest

      - name: Push image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          buildah push ghcr.io/$OWNER/scratch-static-web:latest
